In [15]:
import numpy as np

In [16]:
import numpy as np

# Create a subclass of numpy
class MyNumpy(np.ndarray):pass
    # def __new__(cls, input_array):
    #     obj = np.asarray(input_array).view(cls)
    #     return obj

# Create an instance of the subclass
my_array = np.zeros((10,10)).view(MyNumpy)

# Print the type of the instance
print(my_array)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
%pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [18]:
from tqdm import tqdm
import time

# Define the total number of iterations
total_iterations = 100

# Create a loop with tqdm to track the progress
a =tqdm(range(total_iterations))
#     # Perform some task
#     time.sleep(0.1)  # Simulating some work

#     # Update the progress bar
#     #tqdm.set_postfix({'Progress': f'{i+1}/{total_iterations}'})

# # Print a completion message
# print("Task completed!")


  0%|          | 0/100 [17:18<?, ?it/s]


In [14]:
type(a)

tqdm.std.tqdm

In [19]:
num1 = 3.45
decimal1 = int(num1 % 1 * 100)

num2 = 9.02
decimal2 = int(num2 % 1 * 100)

num3 = 15.1
decimal3 = int(num3 % 1 * 10)

print(decimal1)  # Output: 45
print(decimal2)  # Output: 2
def get_decimal(num):
    decimal = int(num % 1 * 100)
    return decimal

# Test the function
print(get_decimal(3.45))  # Output: 45
print(get_decimal(9.02))  # Output: 2
print(get_decimal(15.1))  # Output: 10
print(decimal3)  # Output: 10


45
1
45
1
9
0
